name: Add release assets

on:
  release:
    types: [published]

jobs:
  add-script-to-release:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Prepare release assets
        run: |
          cp download.ps1 isoDebloater.ps1
          
          echo '@(set "0=%~f0"^)#) & powershell -nop -c iex([io.file]::ReadAllText($env:0)) & exit /b' > isoDebloater.bat
          cat download.ps1 >> isoDebloater.bat
          
      - name: Upload PowerShell script
        run: |
          gh release upload "$TAG" ./isoDebloater.ps1 --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ github.event.release.tag_name }}

      - name: Upload batch script
        run: |
          gh release upload "$TAG" ./isoDebloater.bat --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ github.event.release.tag_name }}
